### ISSUE TITLE
SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by Harliff** [moqmar/i3-alt-tab#1]
Hello. I've installed the i3-alt-tab on Debian 8.0, but it shows error on startup.

("%" is a user shell prompt)

Installation: 
`% sudo npm i -g i3-alt-tab`
`/usr/local/bin/i3-alt-tab -> /usr/local/lib/node_modules/i3-alt-tab/index.js`
`i3-alt-tab@0.1.1 /usr/local/lib/node_modules/i3-alt-tab`
`├── eyespect@0.1.10`
`└── i3@0.2.0 (fastqueue@0.1.0)`

Usage and error:
`% i3-alt-tab`
`/usr/local/lib/node_modules/i3-alt-tab/index.js:26`
`DEBUG&& L(``Focusing window: [id="${win}"] focus``);`
`^`
`SyntaxError: Unexpected token ILLEGAL`
`at Module._compile (module.js:439:25)`
`at Object.Module._extensions..js (module.js:474:10)`
`at Module.load (module.js:356:32)`
`at Function.Module._load (module.js:312:12)`
`at Function.Module.runMain (module.js:497:10)`
`at startup (node.js:119:16)`
`at node.js:906:3`

Versions:
`% npm --version`
`1.4.21`

`% node --version`
`v0.10.29`

**Comment by moqmar** [comment]
node.js only supports template literals from v4.0.0 upwards - more information at http://kangax.github.io/compat-table/es6/#test-template_literals
